# Generated by Django 4.2.3 on 2023-07-04 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='definition',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='term',
            name='word',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='verb',
            name='definition',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='verb',
            name='word',
            field=models.CharField(max_length=400),
        ),
    ]
