# Generated by Django 4.2.3 on 2023-07-05 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_term_definition_alter_term_word_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='verb',
        ),
        migrations.AddField(
            model_name='term',
            name='conjugations',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='term',
            name='wordType',
            field=models.CharField(choices=[('noun', 'Noun'), ('verb', 'Verb'), ('adjective', 'Adjective'), ('adverb', 'Adverb'), ('other', 'Other')], default='other', max_length=400),
        ),
    ]
