# Generated by Django 4.2.3 on 2023-07-05 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_delete_verb_term_conjugations_term_wordtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='tense',
            field=models.CharField(blank=True, choices=[('present', 'present'), ('past', 'past')], default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='wordType',
            field=models.CharField(choices=[('noun', 'noun'), ('verb', 'verb'), ('adjective', 'adjective'), ('adverb', 'adverb'), ('other', 'other')], default='other', max_length=400),
        ),
    ]
