# Generated by Django 4.2.3 on 2023-07-12 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_term_tense_alter_term_wordtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='term',
            name='categories',
            field=models.ManyToManyField(related_name='terms', to='cards.category'),
        ),
    ]
