# Generated by Django 4.2.3 on 2023-07-12 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_category_term_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('beginner', 'beginner'), ('intermediate', 'intermediate'), ('advanced', 'advanced'), ('other', 'other')], default='other', max_length=100),
        ),
    ]
